### PR TITLE
Added Typescript support

### PR DESCRIPTION
**Pull request by deschantkn**

### CODE REVIEW

**Review by cop1fab — CHANGES_REQUESTED** [review]
There are failing checks on this PR.

**Comment by deschantkn** [comment]
> There are failing checks on this PR.
Yeah testing script has to be updated to support Typescript. I didn't do it since there are no tests yet. 
@cop1fab

**Comment by cop1fab** [comment]
> > There are failing checks on this PR.
> > Yeah testing script has to be updated to support Typescript. I didn't do it since there are no tests yet.
> > @cop1fab

Can you then add something simple then test it so that we keep clean develop branch?

**Comment by deschantkn** [comment]
Hi @cop1fab I have configured testing with Typescript. Check is now passing.

**Review by cop1fab — APPROVED** [review]

**Review by nzuwera — APPROVED** [review]

**Pull request merged**
